"""Regenerate resources/geckos.json from the assembly in gen_gecko.py.

Run from the repo root:  python tools/export_geckos.py
Then verify nothing drifted: python tools/verify_geckos.py
"""
import json
import pathlib

import gen_gecko as g

ROOT = pathlib.Path(__file__).resolve().parent.parent

auto_direct = g.assemble(stage_picker=True)
# The lock-in is emitted twice (initial + post-connect re-lock), so the stage
# word appears twice and the app must patch every occurrence.
stage_hits = auto_direct.count("3860001F")
assert stage_hits == 2, f"expected 2 stage words, found {stage_hits}"

out = {
    "_notes": (
        "Generated by tools/gen_gecko.py (keystone). "
        "autoBoot: skip the online mode-select into the Direct CSS. "
        "autoDirect: auto code-entry + search + game-1 stage lock-in; patch "
        "stageWordToken -> 386000XX to change the stage (all occurrences). "
        "charPick[NAME] + charPress together select a character with no human "
        "input. Verify with tools/verify_geckos.py."
    ),
    "_license": ("All gecko payloads here are Peppy's own work, generated by "
                 "tools/gen_gecko.py. No third-party gecko codes are bundled."),
    "autoBoot": g.assemble_boot(3),
    "autoDirect": auto_direct,
    "stageWordToken": "3860001F",
    "stageWordCount": stage_hits,
    "charPress": g.assemble_charpress(),
    "charPick": {name: g.assemble_charpick(name) for name in sorted(g.CHAR_TABLE)},
    "characters": {name: {"ckind": v[0], "x": v[1], "y": v[2]}
                   for name, v in sorted(g.CHAR_TABLE.items())},
}

path = ROOT / "resources" / "geckos.json"
path.write_text(json.dumps(out, indent=1), encoding="utf-8")
print(f"wrote {path}  ({len(out['charPick'])} characters)")
