"""Regenerate resources/geckos.json from the assembly in gen_gecko.py.

Run from the repo root:  python tools/export_geckos.py
Then verify nothing drifted: python tools/verify_geckos.py
"""
import json
import pathlib

import gen_gecko as g

ROOT = pathlib.Path(__file__).resolve().parent.parent

COUNTS = g.costume_counts()
auto_direct = g.assemble(stage_picker=True)
# The lock-in is emitted twice (initial + post-connect re-lock), so the stage
# word appears twice and the app must patch every occurrence.
stage_hits = auto_direct.count("3860001F")
assert stage_hits == 2, f"expected 2 stage words, found {stage_hits}"

auto_random = g.assemble(stage_picker=True, random_stage=True)

# The FOLLOWER build. Exactly one side of a match may take the stage-picking
# role: it maps onto Melee's own ISWINNER/CHOSESTAGE pair, and when both
# clients claimed it, both of them thought they had lost game 1 and both drove
# the stage select for game 2 - which landed on Princess Peach's Castle and
# froze both machines. The follower asserts the winner role and picks nothing.
auto_follow = g.assemble(stage_picker=False)

out = {
    "_notes": (
        "Generated by tools/gen_gecko.py (keystone). "
        "autoBoot: skip the online mode-select into the Direct CSS. "
        "autoDirect: auto code-entry + search + game-1 stage lock-in; patch "
        "stageWordToken -> 386000XX to change the stage (all occurrences). "
        "charPick[NAME] parks the cursor; charPress[NAME] cycles the costume "
        "with X and then presses A - in that order, because the press code "
        "stops once a character is chosen. autoDirectFollow is the same as autoDirect but takes the "
        "winner role and chooses no stage - exactly one side of a match may "
        "pick. Verify with tools/verify_geckos.py."
    ),
    "_license": ("All gecko payloads here are Peppy's own work, generated by "
                 "tools/gen_gecko.py. No third-party gecko codes are bundled."),
    "autoBoot": g.assemble_boot(3),
    "autoDirect": auto_direct,
    "autoDirectRandom": auto_random,      # stage option 3 = the game's own random
    "autoDirectFollow": auto_follow,      # the other side: takes no stage role
    "stageWordToken": "3860001F",
    "stageWordCount": stage_hits,
    "colorToken": "3BE0005B",             # li r31, 0x5B -> patched per match
    # charPress is per character: it waits for the cursor, cycles the costume
    # with X, then presses A - and it needs to know how many costumes exist.
    "charPress": {name: g.assemble_charpress(name, COUNTS[name])
                  for name in sorted(g.CHAR_TABLE)},
    "costumes": {name: COUNTS[name] for name in sorted(g.CHAR_TABLE)},
    "charPick": {name: g.assemble_charpick(name) for name in sorted(g.CHAR_TABLE)},
    "characters": {name: {"ckind": v[0], "x": v[1], "y": v[2]}
                   for name, v in sorted(g.CHAR_TABLE.items())},
}

path = ROOT / "resources" / "geckos.json"
path.write_text(json.dumps(out, indent=1), encoding="utf-8")
print(f"wrote {path}  ({len(out['charPick'])} characters)")
